---
title: "HW3"
author: "Stephen Powers"
date: "9/26/2019"
output: github_document
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

## Problem 1

```{r }
library(readxl)
library(tidyverse)
```

### Importing and Cleaning Data

### *TrashWheel Data*

```{r}
TrashWheel = 
  read_excel(path = "./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                        sheet = 1) %>%
  janitor::clean_names() %>%
  drop_na (dumpster) %>%
  mutate(sports_balls = as.integer(round(sports_balls, digits = 0)))
```

### *2017 Precipitation Data* 


```{r}
Precipitation_2017 =
  read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                        sheet = "2017 Precipitation", skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(total) %>%
  mutate(year = "2017")
```

### *2018 Precipitation Data* 


```{r}
Precipitation_2018 = 
  read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                        sheet = "2018 Precipitation", skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(total) %>%
  mutate(year = "2018")
```

### *Combining Precipitation Data* 

```{r}
Precipitation_2017_2018 = 
  bind_rows(Precipitation_2017, Precipitation_2018) %>%
  mutate(month = month.name[month]) %>%
  select(year, month, total)
```

